import { useMemo, useState } from 'react'
import './App.css'

type Kind='Single SNP'|'Multi S4P'; type Order='Sequential'|'Even Odd'
type Case={id:number;name:string;kind:Kind;file:string;fext:number;next:number;order:Order}
type Params=Record<string,string>; type Result={id:number;name:string;metrics:{name:string;value:string;status:'PASS'|'FAIL'}[]}
const fields=[['symbolRate','Symbol Rate (fb)','GBaud'],['ilPre','IL pre channel','dB'],['ilPost','IL post channel','dB'],['scaling','Scaling factor',''],['aft','Aft','mV'],['ant','Ant','mV'],['ft','ft','GHz'],['fr','fr','GHz'],['tfr','Tfr','ps'],['tnr','Tnr','ps'],['fstart','Fstart','GHz'],['fstop','Fstop','GHz'],['df','df','GHz']] as const
const specs:Record<string,Params>={
 'PCIe6 Cable Connector':{symbolRate:'32',ilPre:'25',ilPost:'9.46',scaling:'0.745355992',aft:'800',ant:'1000',ft:'31.53',fr:'24',tfr:'9.27',tnr:'9.27',fstart:'0.01',fstop:'24',df:'0.01'},
 'PCIe6 Add-in Card':{symbolRate:'32',ilPre:'13',ilPost:'10',scaling:'0.75',aft:'800',ant:'1000',ft:'31.5',fr:'24',tfr:'9.5',tnr:'9.5',fstart:'0.01',fstop:'24',df:'0.01'},
 'PCIe6 System Board':{symbolRate:'32',ilPre:'18',ilPost:'8',scaling:'0.72',aft:'800',ant:'1000',ft:'31',fr:'24',tfr:'9.8',tnr:'9.8',fstart:'0.01',fstop:'24',df:'0.01'},
 'PCIe5 Cable Connector':{symbolRate:'16',ilPre:'20',ilPost:'8',scaling:'0.7',aft:'800',ant:'1000',ft:'16',fr:'12',tfr:'18.5',tnr:'18.5',fstart:'0.01',fstop:'12',df:'0.01'}}
const seed:Case[]=[{id:1,name:'Case 1',kind:'Single SNP',file:'DUT_SIM.s16p',fext:4,next:4,order:'Sequential'},{id:2,name:'Case 2',kind:'Multi S4P',file:'',fext:4,next:4,order:'Even Odd'}]
function mockResults(cases:Case[]):Result[]{const nums=[['123.456','456.777','123.888'],['198.204','221.350','97.624'],['142.832','312.090','110.452']];return cases.map((c,i)=>({id:c.id,name:c.name,metrics:['Total ccICN','ccICN_NEXT','ccICN_FEXT'].map((name,j)=>({name,value:nums[i%3][j],status:(i+j)%3===1?'FAIL':'PASS'}))}))}

export default function App(){
 const [cases,setCases]=useState(seed),[spec,setSpec]=useState('PCIe6 Cable Connector'),[params,setParams]=useState<Params>({...specs['PCIe6 Cable Connector']})
 const [caseEdit,setCaseEdit]=useState<Case|null|'new'>(null),[specOpen,setSpecOpen]=useState(false),[powerOpen,setPowerOpen]=useState(false)
 const [results,setResults]=useState<Result[]>([]),[resultSpec,setResultSpec]=useState(''),[expanded,setExpanded]=useState<Set<number>>(new Set()),[loading,setLoading]=useState(false),[toast,setToast]=useState('')
 const modified=useMemo(()=>!!spec&&fields.some(([k])=>params[k]!==specs[spec][k]),[params,spec]); const reason=!cases.length?'Add at least one case.':!spec?'Select a specification preset.':''
 const saveCase=(draft:Case)=>{if(caseEdit==='new')setCases(c=>[...c,{...draft,id:Date.now(),name:`Case ${c.length+1}`}]);else setCases(c=>c.map(x=>x.id===draft.id?draft:x));setCaseEdit(null)}
 const calculate=()=>{if(reason)return;setLoading(true);setTimeout(()=>{const r=mockResults(cases);setResults(r);setExpanded(new Set(r.map(x=>x.id)));setResultSpec(`Spec: ${spec}${modified?' — Modified':''}`);setLoading(false)},850)}
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)}
 const copy=async()=>{const rows=['Case\tMetric\tResult\tUnit\tStatus',...results.flatMap(r=>r.metrics.map(m=>`${r.name}\t${m.name}\t${m.value}\tµV\t${m.status}`))];try{await navigator.clipboard.writeText(rows.join('\n'));notify('Results copied to clipboard.')}catch{notify('Unable to access clipboard.')}}
 return <main className="shell"><header><div><small>CHANNEL METRIC TOOL</small><h1>ccICN Tool</h1></div><span className="prototype">UX Prototype</span></header><div className="card">
  <section><Heading n="1" title="Step 1: Select Files" desc="Add one or more cases for ccICN analysis."/><div className="toolbar"><button className="primary" onClick={()=>setCaseEdit('new')}>＋ Add Case</button><span>{cases.length} case(s) added</span><button className="secondary right" disabled={!cases.length} onClick={()=>{setCases([]);setResults([])}}>Clear All</button></div><div className="case-list">{cases.length?cases.map(c=><div className="case-row" key={c.id}><strong>{c.name}</strong><span>{c.kind}</span><span className="muted">{c.kind==='Single SNP'?c.file:`${c.fext} FEXT, ${c.next} NEXT`}</span><button className="link" onClick={()=>setCaseEdit(c)}>View / Edit</button><button className="link danger" onClick={()=>{setCases(x=>x.filter(y=>y.id!==c.id));setResults([])}}>Remove</button></div>):<div className="empty">No cases added. Select “Add Case” to begin.</div>}</div></section>
  <section><Heading n="2" title="Step 2: ccICN parameters" desc="Select a specification preset and review or modify the parameters."/><div className="spec-row"><button className="secondary" onClick={()=>setSpecOpen(true)}>Select Specification</button><span>Selected: <strong>{spec||'None'}</strong></span>{modified&&<b className="modified">Modified</b>}</div><div className="param-grid">{fields.map(([k,label,unit])=><label className="param" key={k}><span>{label}</span><input value={params[k]||''} onChange={e=>setParams({...params,[k]:e.target.value})}/><span className="muted">{unit}</span></label>)}</div><div className="calc"><button className="primary" disabled={!!reason||loading} title={reason} onClick={calculate}>{loading?'Calculating...':'Calculate'}</button></div></section>
  <section><div className="results-head"><Heading n="3" title="Step 3: Results" desc="Review ccICN results for each calculated case."/><div className="actions"><button className="secondary" disabled={!results.length} onClick={()=>setPowerOpen(true)}>View Power Sum</button><button className="secondary" disabled={!results.length} onClick={copy}>Copy Sheet</button><button className="secondary" disabled={!results.length} onClick={()=>notify('Copy Picture is prototype only.')}>Copy Picture</button></div></div>{results.length?<><div className="result-spec">{resultSpec}</div><div className="result-list">{results.map(r=>{const open=expanded.has(r.id);return <div className="result" key={r.id}><button className="result-title" onClick={()=>setExpanded(old=>{const n=new Set(old);if(open)n.delete(r.id);else n.add(r.id);return n})}><i className={open?'open':''}>›</i>{r.name}</button>{open&&<div className="metrics"><div className="metric labels"><span>Metric</span><span>Result</span><span>Unit</span><span>Status</span></div>{r.metrics.map(m=><div className="metric" key={m.name}><strong>{m.name}</strong><span>{m.value}</span><span>µV</span><span><b className={`status ${m.status.toLowerCase()}`}>{m.status}</b></span></div>)}</div>}</div>})}</div></>:<div className="results-empty">Results will appear here after calculation.</div>}</section>
 </div>{caseEdit&&<CaseDialog value={caseEdit==='new'?{id:0,name:'',kind:'Single SNP',file:'DUT_SIM.s16p',fext:4,next:4,order:'Sequential'}:caseEdit} close={()=>setCaseEdit(null)} save={saveCase}/>} {specOpen&&<Modal title="Select Specification" close={()=>setSpecOpen(false)}><p>Choose a preset to populate all ccICN parameters.</p><div className="presets">{Object.keys(specs).map(name=><button className={name===spec?'selected':''} key={name} onClick={()=>{setSpec(name);setParams({...specs[name]});setSpecOpen(false)}}><span>{name}</span>{name===spec&&<span>✓</span>}</button>)}</div></Modal>}{powerOpen&&<Modal title="Power Sum" wide close={()=>setPowerOpen(false)}><p>Mock frequency response for UX evaluation only.</p><Chart/></Modal>}{toast&&<div className="toast">{toast}</div>}</main>
}
function Heading({n,title,desc}:{n:string;title:string;desc:string}){return <div className="heading"><b>{n}</b><div><h2>{title}</h2><p>{desc}</p></div></div>}
function Modal({title,children,close,wide=false}:{title:string;children:React.ReactNode;close:()=>void;wide?:boolean}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function CaseDialog({value,close,save}:{value:Case;close:()=>void;save:(c:Case)=>void}){const[d,setD]=useState({...value});const valid=d.kind==='Single SNP'?!!d.file.trim():d.fext>0&&d.next>0;return <Modal title={value.id?`Edit ${value.name}`:'Add Case'} close={close}><div className="form"><fieldset><legend>Input Type</legend><div className="radio"><label><input type="radio" checked={d.kind==='Single SNP'} onChange={()=>setD({...d,kind:'Single SNP'})}/> Single SNP</label><label><input type="radio" checked={d.kind==='Multi S4P'} onChange={()=>setD({...d,kind:'Multi S4P'})}/> Multi S4P</label></div></fieldset>{d.kind==='Single SNP'?<label className="modal-field">Filename<input value={d.file} onChange={e=>setD({...d,file:e.target.value})}/><small>Mock selection supports .s8p, .s16p, or .s32p filenames.</small></label>:<div className="dual"><label className="modal-field">FEXT files<input type="number" min="1" value={d.fext} onChange={e=>setD({...d,fext:+e.target.value})}/></label><label className="modal-field">NEXT files<input type="number" min="1" value={d.next} onChange={e=>setD({...d,next:+e.target.value})}/></label></div>}<fieldset><legend>Port Order</legend><div className="radio"><label><input type="radio" checked={d.order==='Sequential'} onChange={()=>setD({...d,order:'Sequential'})}/> Sequential</label><label><input type="radio" checked={d.order==='Even Odd'} onChange={()=>setD({...d,order:'Even Odd'})}/> Even Odd</label></div></fieldset></div><div className="modal-foot"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!valid} onClick={()=>save(d)}>{value.id?'Save Changes':'Add Case'}</button></div></Modal>}
function Chart(){return <div className="chart"><svg viewBox="0 0 660 330"><defs><linearGradient id="area" x2="0" y2="1"><stop stopColor="#2f6fed" stopOpacity=".22"/><stop offset="1" stopColor="#2f6fed" stopOpacity="0"/></linearGradient></defs>{[55,110,165,220,275].map(y=><line key={y} x1="62" y1={y} x2="630" y2={y}/>) }<path className="area" d="M62 247 C105 236 123 219 158 225 S216 199 249 206 S307 167 340 181 S400 142 438 151 S493 111 526 125 S583 77 630 83 L630 275 L62 275Z"/><path className="curve" d="M62 247 C105 236 123 219 158 225 S216 199 249 206 S307 167 340 181 S400 142 438 151 S493 111 526 125 S583 77 630 83"/><line x1="62" y1="24" x2="62" y2="275"/><line x1="62" y1="275" x2="630" y2="275"/>{[0,6,12,18,24].map((x,i)=><text key={x} x={62+i*142} y="298" textAnchor="middle">{x}</text>)}<text x="346" y="324" textAnchor="middle">Frequency (GHz)</text><text x="16" y="160" textAnchor="middle" transform="rotate(-90 16 160)">Power Sum (dB)</text></svg></div>}
