import { useMemo, useState } from 'react'
import './App.css'
import './ParamLayout.css'
import './AddCase.css'
import './SpecDialog.css'

type Kind='Single SNP'|'Multi S4P'; type Order='Sequential'|'Even Odd'
type Case={id:number;name:string;kind:Kind;file:string;fextFiles:string[];nextFiles:string[];order:Order}
type Params=Record<string,string>; type Result={id:number;name:string;metrics:{name:string;value:string;status:'PASS'|'FAIL'}[]}
const fields=[['symbolRate','Symbol Rate (fb)','GBaud'],['ilPre','IL pre channel','dB'],['ilPost','IL post channel','dB'],['scaling','Scaling factor',''],['aft','Aft','mV'],['ant','Ant','mV'],['ft','ft','GHz'],['fr','fr','GHz'],['tfr','Tfr','ps'],['tnr','Tnr','ps'],['fstart','Fstart','GHz'],['fstop','Fstop','GHz'],['df','df','GHz']] as const
const specs:Record<string,Params>={
 'PCIe6 Cable Connector':{symbolRate:'32',ilPre:'25',ilPost:'9.46',scaling:'0.745355992',aft:'800',ant:'1000',ft:'31.53',fr:'24',tfr:'9.27',tnr:'9.27',fstart:'0.01',fstop:'24',df:'0.01'},
 'PCIe6 Add-in Card':{symbolRate:'32',ilPre:'13',ilPost:'10',scaling:'0.75',aft:'800',ant:'1000',ft:'31.5',fr:'24',tfr:'9.5',tnr:'9.5',fstart:'0.01',fstop:'24',df:'0.01'},
 'PCIe6 System Board':{symbolRate:'32',ilPre:'18',ilPost:'8',scaling:'0.72',aft:'800',ant:'1000',ft:'31',fr:'24',tfr:'9.8',tnr:'9.8',fstart:'0.01',fstop:'24',df:'0.01'},
 'PCIe5 Cable Connector':{symbolRate:'16',ilPre:'20',ilPost:'8',scaling:'0.7',aft:'800',ant:'1000',ft:'16',fr:'12',tfr:'18.5',tnr:'18.5',fstart:'0.01',fstop:'12',df:'0.01'}}
const specCatalog=Object.keys(specs).map(name=>{const generation=name.split(' ')[0];return{name,generation,application:name.slice(generation.length+1)}})
const seed:Case[]=[{id:1,name:'Case 1',kind:'Single SNP',file:'DUT_SIM.s16p',fextFiles:[],nextFiles:[],order:'Sequential'},{id:2,name:'Case 2',kind:'Multi S4P',file:'',fextFiles:['FEXT_01.s4p','FEXT_02.s4p','FEXT_03.s4p','FEXT_04.s4p'],nextFiles:['NEXT_01.s4p','NEXT_02.s4p','NEXT_03.s4p','NEXT_04.s4p'],order:'Even Odd'}]
function mockResults(cases:Case[]):Result[]{const nums=[['123.456','456.777','123.888'],['198.204','221.350','97.624'],['142.832','312.090','110.452']];return cases.map((c,i)=>({id:c.id,name:c.name,metrics:['Total ccICN','ccICN_NEXT','ccICN_FEXT'].map((name,j)=>({name,value:nums[i%3][j],status:(i+j)%3===1?'FAIL':'PASS'}))}))}

export default function App(){
 const [cases,setCases]=useState(seed),[spec,setSpec]=useState('PCIe6 Cable Connector'),[params,setParams]=useState<Params>({...specs['PCIe6 Cable Connector']})
 const [caseEdit,setCaseEdit]=useState<Case|null|'new'>(null),[specOpen,setSpecOpen]=useState(false),[powerOpen,setPowerOpen]=useState(false)
 const [results,setResults]=useState<Result[]>([]),[resultSpec,setResultSpec]=useState(''),[expanded,setExpanded]=useState<Set<number>>(new Set()),[loading,setLoading]=useState(false),[toast,setToast]=useState('')
 const modified=useMemo(()=>!!spec&&fields.some(([k])=>params[k]!==specs[spec][k]),[params,spec]); const reason=!cases.length?'Add at least one case.':!spec?'Select a specification preset.':''
 const saveCase=(draft:Case)=>{if(caseEdit==='new')setCases(c=>[...c,{...draft,id:Date.now(),name:`Case ${c.length+1}`}]);else setCases(c=>c.map(x=>x.id===draft.id?draft:x));setCaseEdit(null)}
 const calculate=()=>{if(reason)return;setLoading(true);setTimeout(()=>{const r=mockResults(cases);setResults(r);setExpanded(new Set(r.map(x=>x.id)));setResultSpec(`Spec: ${spec}${modified?' — Modified':''}`);setLoading(false)},850)}
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)}
 const copy=async()=>{const rows=['Case\tMetric\tResult\tUnit\tStatus',...results.flatMap(r=>r.metrics.map(m=>`${r.name}\t${m.name}\t${m.value}\tµV\t${m.status}`))];try{await navigator.clipboard.writeText(rows.join('\n'));notify('Results copied to clipboard.')}catch{notify('Unable to access clipboard.')}}
 const parameter=(key:string,label:string,unit:string)=><label className="param" key={key}><span>{label}</span><input value={params[key]||''} onChange={e=>setParams({...params,[key]:e.target.value})}/><span className="muted">{unit}</span></label>
 return <main className="shell"><header><div><small>CHANNEL METRIC TOOL</small><h1>ccICN Tool</h1></div><span className="prototype">UX Prototype</span></header><div className="card">
  <section><Heading n="1" title="Step 1: Select Files" desc="Add one or more cases for ccICN analysis."/><div className="toolbar"><button className="primary" onClick={()=>setCaseEdit('new')}>＋ Add Case</button><span>{cases.length} case(s) added</span><button className="secondary right" disabled={!cases.length} onClick={()=>{setCases([]);setResults([])}}>Clear All</button></div><div className="case-list">{cases.length?cases.map(c=><div className="case-row" key={c.id}><strong>{c.name}</strong><span>{c.kind}</span><span className="muted">{c.kind==='Single SNP'?c.file:`${c.fextFiles.length} FEXT, ${c.nextFiles.length} NEXT`}</span><button className="link" onClick={()=>setCaseEdit(c)}>View / Edit</button><button className="link danger" onClick={()=>{setCases(x=>x.filter(y=>y.id!==c.id));setResults([])}}>Remove</button></div>):<div className="empty">No cases added. Select “Add Case” to begin.</div>}</div></section>
  <section><Heading n="2" title="Step 2: ccICN parameters" desc="Select a specification preset and review or modify the parameters."/><div className="spec-row"><button className="secondary" onClick={()=>setSpecOpen(true)}>Select Specification</button><span>Selected: <strong>{spec||'None'}</strong></span>{modified&&<b className="modified">Modified</b>}</div><div className="param-layout"><div className="param-primary">{parameter('symbolRate','Symbol Rate (fb)','GBaud')}{parameter('ilPre','IL pre channel','dB')}{parameter('ilPost','IL post channel','dB')}</div><div className="param-scaling">{parameter('scaling','Scaling factor','')}</div><div className="param-pairs"><div>{parameter('aft','Aft','mV')}{parameter('ant','Ant','mV')}</div><div>{parameter('ft','ft','GHz')}{parameter('fr','fr','GHz')}</div><div>{parameter('tfr','Tfr','ps')}{parameter('tnr','Tnr','ps')}</div></div><div className="param-frequencies">{parameter('fstart','Fstart','GHz')}{parameter('fstop','Fstop','GHz')}{parameter('df','df','GHz')}</div></div><div className="calc"><button className="primary" disabled={!!reason||loading} title={reason} onClick={calculate}>{loading?'Calculating...':'Calculate'}</button></div></section>
  <section><div className="results-head"><Heading n="3" title="Step 3: Results" desc="Review ccICN results for each calculated case."/><div className="actions"><button className="secondary" disabled={!results.length} onClick={()=>setPowerOpen(true)}>View Power Sum</button><button className="secondary" disabled={!results.length} onClick={copy}>Copy Sheet</button><button className="secondary" disabled={!results.length} onClick={()=>notify('Copy Picture is prototype only.')}>Copy Picture</button></div></div>{results.length?<><div className="result-spec">{resultSpec}</div><div className="result-list">{results.map(r=>{const open=expanded.has(r.id);return <div className="result" key={r.id}><button className="result-title" onClick={()=>setExpanded(old=>{const n=new Set(old);if(open)n.delete(r.id);else n.add(r.id);return n})}><i className={open?'open':''}>›</i>{r.name}</button>{open&&<div className="metrics"><div className="metric labels"><span>Metric</span><span>Result</span><span>Unit</span><span>Status</span></div>{r.metrics.map(m=><div className="metric" key={m.name}><strong>{m.name}</strong><span>{m.value}</span><span>µV</span><span><b className={`status ${m.status.toLowerCase()}`}>{m.status}</b></span></div>)}</div>}</div>})}</div></>:<div className="results-empty">Results will appear here after calculation.</div>}</section>
 </div>{caseEdit&&<CaseDialog value={caseEdit==='new'?{id:0,name:'',kind:'Single SNP',file:'',fextFiles:[],nextFiles:[],order:'Sequential'}:caseEdit} close={()=>setCaseEdit(null)} save={saveCase}/>} {specOpen&&<SpecDialog current={spec} close={()=>setSpecOpen(false)} select={name=>{setSpec(name);setParams({...specs[name]});setSpecOpen(false)}}/>}{powerOpen&&<Modal title="Power Sum" wide close={()=>setPowerOpen(false)}><p>Mock frequency response for UX evaluation only.</p><Chart/></Modal>}{toast&&<div className="toast">{toast}</div>}</main>
}
function Heading({n,title,desc}:{n:string;title:string;desc:string}){return <div className="heading"><b>{n}</b><div><h2>{title}</h2><p>{desc}</p></div></div>}
function Modal({title,children,close,wide=false,dialogClass='' }:{title:string;children:React.ReactNode;close:()=>void;wide?:boolean;dialogClass?:string}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`modal ${wide?'wide':''} ${dialogClass}`} role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button aria-label="Close" onClick={close}>×</button></div>{children}</div></div>}
function SpecDialog({current,close,select}:{current:string;close:()=>void;select:(name:string)=>void}){
 const[query,setQuery]=useState(''),[highlighted,setHighlighted]=useState(current)
 const matches=(name:string,generation:string,application:string,text:string)=>`${name} ${generation} ${application}`.toLowerCase().includes(text.trim().toLowerCase())
 const visible=specCatalog.filter(item=>matches(item.name,item.generation,item.application,query))
 const preview=highlighted?specs[highlighted]:null
 const updateSearch=(text:string)=>{setQuery(text);if(highlighted){const item=specCatalog.find(entry=>entry.name===highlighted);if(item&&!matches(item.name,item.generation,item.application,text))setHighlighted('')}}
 return <Modal title="Select spec" wide dialogClass="spec-modal" close={close}><div className="spec-dialog"><div className="spec-left"><label className="search-field"><span>Search</span><input type="search" placeholder="Search specifications" value={query} onChange={e=>updateSearch(e.target.value)}/></label><div className="spec-table"><div className="spec-table-head"><span>Spec</span><span>Generation</span><span>Application</span></div><div className="spec-table-body">{visible.length?visible.map(item=><button className={`spec-table-row ${highlighted===item.name?'highlighted':''}`} key={item.name} onClick={()=>setHighlighted(item.name)}><span>{item.name}</span><span>{item.generation}</span><span>{item.application}</span></button>):<div className="spec-empty">No matching specifications.</div>}</div></div></div><aside className="spec-detail"><h3>Detail:</h3>{preview?<div className="detail-values">{fields.map(([key,label,unit])=><div key={key}><span>{label}:</span><strong>{preview[key]}{unit&&<small> {unit}</small>}</strong></div>)}</div>:<p>Highlight a specification to preview its parameters.</p>}</aside></div><div className="modal-foot"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!highlighted} onClick={()=>highlighted&&select(highlighted)}>Select</button></div></Modal>
}
function CaseDialog({value,close,save}:{value:Case;close:()=>void;save:(c:Case)=>void}){
 const[d,setD]=useState({...value,fextFiles:[...value.fextFiles],nextFiles:[...value.nextFiles]})
 const valid=d.kind==='Single SNP'?Boolean(d.file&&d.order):Boolean((d.fextFiles.length||d.nextFiles.length)&&d.order)
 const switchMode=(kind:Kind)=>setD({...d,kind,order:kind==='Single SNP'?'Sequential':'Even Odd'})
 const selectFiles=(list:FileList|null,target:'snp'|'fext'|'next')=>{const names=Array.from(list||[]).map(file=>file.name);if(target==='snp')setD({...d,file:names[0]||''});else setD({...d,[target==='fext'?'fextFiles':'nextFiles']:names})}
 const fileGroup=(label:string,target:'fext'|'next',files:string[])=><div className="file-group"><strong>{label}</strong><div className="browse-row"><label className="secondary browse-button">Browse {label}...<input type="file" accept=".s4p" multiple onChange={e=>selectFiles(e.target.files,target)}/></label><span>{files.length} file(s) selected</span><button className="link danger right" disabled={!files.length} onClick={()=>setD({...d,[target==='fext'?'fextFiles':'nextFiles']:[]})}>Clear All</button></div>{files.length>0&&<div className="modal-file-list">{files.map((file,index)=><div className="modal-file-row" key={`${file}-${index}`}><span>{file}</span><button className="link danger" onClick={()=>setD({...d,[target==='fext'?'fextFiles':'nextFiles']:files.filter((_,i)=>i!==index)})}>Remove</button></div>)}</div>}</div>
 return <Modal title={value.id?`Edit ${value.name}`:'Add Case'} wide close={close}><div className="case-dialog">
  <section className="dialog-section"><h3>Step 1-1: select files</h3><div className="mode-options"><label><input type="radio" checked={d.kind==='Single SNP'} onChange={()=>switchMode('Single SNP')}/> Select sNp file</label><label><input type="radio" checked={d.kind==='Multi S4P'} onChange={()=>switchMode('Multi S4P')}/> Select multiple s4p file</label></div>
  {d.kind==='Single SNP'?<div className="file-group"><div className="browse-row"><label className="secondary browse-button">Browse sNp File...<input type="file" accept=".s4p,.s8p,.s16p,.s32p" onChange={e=>selectFiles(e.target.files,'snp')}/></label><span>{d.file||'No file selected'}</span><button className="link danger right" disabled={!d.file} onClick={()=>setD({...d,file:''})}>Clear All</button></div>{d.file&&<div className="modal-file-list"><div className="modal-file-row"><span>{d.file}</span><button className="link danger" onClick={()=>setD({...d,file:''})}>Remove</button></div></div>}</div>:<div className="multi-files">{fileGroup('FEXT Files','fext',d.fextFiles)}{fileGroup('NEXT Files','next',d.nextFiles)}</div>}</section>
  {d.kind==='Single SNP'&&<section className="dialog-section pinmap"><h3>Step 1-2: set pinmap</h3><div className="pinmap-reserved">Pinmap configuration will be added in a later prototype iteration.</div></section>}
  <section className="dialog-section"><h3>{d.kind==='Single SNP'?'Step 1-3: set port order':'Step 1-2: set port order'}</h3><label className="order-field"><span>Port Order</span><select value={d.order} onChange={e=>setD({...d,order:e.target.value as Order})}><option>Sequential</option><option>Even Odd</option></select></label></section>
 </div><div className="modal-foot"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!valid} title={!valid?'Select at least one valid input file.':''} onClick={()=>save(d)}>Save</button></div></Modal>
}
function Chart(){return <div className="chart"><svg viewBox="0 0 660 330"><defs><linearGradient id="area" x2="0" y2="1"><stop stopColor="#2f6fed" stopOpacity=".22"/><stop offset="1" stopColor="#2f6fed" stopOpacity="0"/></linearGradient></defs>{[55,110,165,220,275].map(y=><line key={y} x1="62" y1={y} x2="630" y2={y}/>) }<path className="area" d="M62 247 C105 236 123 219 158 225 S216 199 249 206 S307 167 340 181 S400 142 438 151 S493 111 526 125 S583 77 630 83 L630 275 L62 275Z"/><path className="curve" d="M62 247 C105 236 123 219 158 225 S216 199 249 206 S307 167 340 181 S400 142 438 151 S493 111 526 125 S583 77 630 83"/><line x1="62" y1="24" x2="62" y2="275"/><line x1="62" y1="275" x2="630" y2="275"/>{[0,6,12,18,24].map((x,i)=><text key={x} x={62+i*142} y="298" textAnchor="middle">{x}</text>)}<text x="346" y="324" textAnchor="middle">Frequency (GHz)</text><text x="16" y="160" textAnchor="middle" transform="rotate(-90 16 160)">Power Sum (dB)</text></svg></div>}
